import type { CodeProfile } from "../checks/types";
import type { Platform, PlatformDetection } from "./types";

interface Rule {
  platform: Platform;
  detect(
    paths: Set<string>,
    deps: Record<string, string>,
    content: Map<string, string>,
  ): { confidence: number; signals: string[] } | null;
}

// Each rule returns { confidence, signals } if the platform is detected,
// or null if not. Rules are tested in order; first non-null result wins
// (platforms are mutually exclusive in practice).
const RULES: Rule[] = [
  // ── Cursor ────────────────────────────────────────────────────────────────
  {
    platform: "cursor",
    detect(paths) {
      const signals: string[] = [];
      if (paths.has(".cursorrules")) signals.push(".cursorrules file");
      if ([...paths].some(p => p.startsWith(".cursor/"))) signals.push(".cursor/ directory");
      if (!signals.length) return null;
      return { confidence: signals.length >= 2 ? 95 : 85, signals };
    },
  },

  // ── Bolt ──────────────────────────────────────────────────────────────────
  {
    platform: "bolt",
    detect(paths, deps) {
      const signals: string[] = [];
      if ([...paths].some(p => p.startsWith(".bolt/"))) signals.push(".bolt/ directory");
      if (paths.has("bolt.config.js") || paths.has("bolt.config.ts") || paths.has("bolt.config.json"))
        signals.push("bolt.config file");
      if (Object.keys(deps).some(d => d.startsWith("@bolt/"))) signals.push("@bolt/* dependency");
      if (!signals.length) return null;
      return { confidence: signals.length >= 2 ? 92 : 82, signals };
    },
  },

  // ── Lovable ───────────────────────────────────────────────────────────────
  {
    platform: "lovable",
    detect(paths, deps) {
      const signals: string[] = [];
      if (paths.has("lovable.config.ts") || paths.has("lovable.config.js")) signals.push("lovable.config file");
      if (paths.has(".lovable")) signals.push(".lovable file");
      if ([...paths].some(p => p.startsWith("public/lovable-uploads/"))) signals.push("public/lovable-uploads/ directory");
      if ("lovable-tagger" in deps) signals.push("lovable-tagger dependency");
      if (Object.keys(deps).some(d => d.startsWith("@lovable/"))) signals.push("@lovable/* dependency");
      if (!signals.length) return null;
      return { confidence: signals.length >= 2 ? 92 : 80, signals };
    },
  },

  // ── Replit ────────────────────────────────────────────────────────────────
  {
    platform: "replit",
    detect(paths) {
      const signals: string[] = [];
      if (paths.has(".replit")) signals.push(".replit file");
      if (paths.has("replit.nix")) signals.push("replit.nix file");
      if ([...paths].some(p => p.startsWith(".config/") && p.includes("replit"))) signals.push(".config/replit");
      if (!signals.length) return null;
      return { confidence: signals.length >= 2 ? 95 : 88, signals };
    },
  },

  // ── v0 (Vercel) ───────────────────────────────────────────────────────────
  {
    platform: "v0",
    detect(paths, _, content) {
      const signals: string[] = [];
      if (paths.has("v0.config.ts") || paths.has("v0.config.js")) signals.push("v0.config file");
      const componentsJson = content.get("components.json");
      if (componentsJson && /registry\.v0\.dev/.test(componentsJson)) signals.push("registry.v0.dev in components.json");
      // v0 often leaves a comment in generated files
      for (const text of content.values()) {
        if (/Generated by v0/i.test(text)) { signals.push("Generated by v0 comment"); break; }
      }
      if (!signals.length) return null;
      return { confidence: signals.length >= 2 ? 90 : 78, signals };
    },
  },

  // ── Base44 ────────────────────────────────────────────────────────────────
  {
    platform: "base44",
    detect(paths, deps) {
      const signals: string[] = [];
      if (paths.has("base44.json") || paths.has("base44.config.js") || paths.has("base44.config.ts"))
        signals.push("base44 config file");
      if ("@base44/sdk" in deps || "base44" in deps) signals.push("base44 dependency");
      if (paths.has(".base44")) signals.push(".base44 file");
      if (!signals.length) return null;
      return { confidence: signals.length >= 2 ? 90 : 80, signals };
    },
  },

  // ── Claude Code ───────────────────────────────────────────────────────────
  {
    platform: "claude-code",
    detect(paths) {
      const signals: string[] = [];
      if ([...paths].some(p => p.startsWith(".claude/"))) signals.push(".claude/ directory");
      if (paths.has("CLAUDE.md")) signals.push("CLAUDE.md file");
      if (!signals.length) return null;
      return { confidence: signals.length >= 2 ? 90 : 80, signals };
    },
  },
];

export function detectPlatform(profile: CodeProfile): PlatformDetection {
  const paths = new Set(profile.files.map(f => f.path));
  const deps = profile.dependencies;
  const content = new Map<string, string>(
    profile.files.filter(f => f.content).map(f => [f.path, f.content]),
  );

  for (const rule of RULES) {
    const result = rule.detect(paths, deps, content);
    if (result) {
      return { platform: rule.platform, confidence: result.confidence, signals: result.signals };
    }
  }

  return { platform: "unknown", confidence: 0, signals: [] };
}
