import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { buildCodeProfile } from "../checks/profile";
import { buildFingerprint, detectPlatform, inferModel, computeAiRatio } from "../fingerprint";
import type { CodeProfile, GitCommit } from "../checks/types";

// ── fixture helpers ───────────────────────────────────────────────────────────

const FIXTURE_ROOT = join(tmpdir(), "shiprank-fingerprint-fixtures");

function ensureDir(d: string) { mkdirSync(d, { recursive: true }); }
function writeText(p: string, t: string) { writeFileSync(p, t, "utf8"); }
function writeJson(p: string, d: unknown) { writeFileSync(p, JSON.stringify(d, null, 2), "utf8"); }

beforeAll(() => {
  rmSync(FIXTURE_ROOT, { recursive: true, force: true });

  // ── cursor ────────────────────────────────────────────────────────────────
  const cursor = join(FIXTURE_ROOT, "cursor-app");
  ensureDir(cursor);
  writeText(join(cursor, ".cursorrules"), "You are an expert TypeScript engineer.\nFollow Next.js best practices.");
  writeJson(join(cursor, "package.json"), { name: "cursor-app", dependencies: { next: "14.2.0" } });

  // ── bolt ──────────────────────────────────────────────────────────────────
  const bolt = join(FIXTURE_ROOT, "bolt-app");
  ensureDir(join(bolt, ".bolt"));
  writeJson(join(bolt, ".bolt", "config.json"), { version: 1 });
  writeJson(join(bolt, "package.json"), { name: "bolt-app", dependencies: { react: "18.3.0" } });

  // ── lovable ───────────────────────────────────────────────────────────────
  const lovable = join(FIXTURE_ROOT, "lovable-app");
  ensureDir(lovable);
  writeText(join(lovable, "lovable.config.ts"), "export default { projectId: 'abc123' };");
  writeJson(join(lovable, "package.json"), { name: "lovable-app", devDependencies: { "lovable-tagger": "1.0.0" } });

  // ── replit ────────────────────────────────────────────────────────────────
  const replit = join(FIXTURE_ROOT, "replit-app");
  ensureDir(replit);
  writeText(join(replit, ".replit"), '[run]\ncommand = "node index.js"\n');
  writeJson(join(replit, "package.json"), { name: "replit-app", dependencies: { express: "4.19.0" } });

  // ── v0 ────────────────────────────────────────────────────────────────────
  const v0 = join(FIXTURE_ROOT, "v0-app");
  ensureDir(join(v0, "components"));
  writeText(join(v0, "v0.config.ts"), "export default { registry: 'registry.v0.dev' };");
  writeJson(join(v0, "package.json"), { name: "v0-app", dependencies: { next: "14.2.0" } });
  // Also add a component with the Generated-by comment to test multi-signal boost
  writeText(join(v0, "components", "Hero.tsx"), "// Generated by v0\nexport function Hero() { return <div /> }");

  // ── base44 ────────────────────────────────────────────────────────────────
  const base44 = join(FIXTURE_ROOT, "base44-app");
  ensureDir(base44);
  writeJson(join(base44, "base44.json"), { version: "1.0.0", appId: "xyz" });
  writeJson(join(base44, "package.json"), { name: "base44-app", dependencies: { "@base44/sdk": "2.0.0" } });

  // ── claude-code ───────────────────────────────────────────────────────────
  const cc = join(FIXTURE_ROOT, "claude-code-app");
  ensureDir(join(cc, ".claude"));
  writeJson(join(cc, ".claude", "settings.json"), { permissions: [] });
  writeText(join(cc, "CLAUDE.md"), "# Project\nThis is a Claude Code project.");
  writeJson(join(cc, "package.json"), { name: "claude-code-app", dependencies: { next: "14.2.0" } });

  // ── unknown ───────────────────────────────────────────────────────────────
  const unknown = join(FIXTURE_ROOT, "unknown-app");
  ensureDir(unknown);
  writeJson(join(unknown, "package.json"), { name: "unknown-app", dependencies: { react: "18.3.0" } });
});

afterAll(() => {
  rmSync(FIXTURE_ROOT, { recursive: true, force: true });
});

// ── Platform detection — all 7 fixtures ──────────────────────────────────────

describe("detectPlatform — all 7 platform fixtures", () => {
  it("cursor: .cursorrules → platform cursor, confidence >= 80", async () => {
    const profile = await buildCodeProfile(join(FIXTURE_ROOT, "cursor-app"));
    const d = detectPlatform(profile);
    expect(d.platform).toBe("cursor");
    expect(d.confidence).toBeGreaterThanOrEqual(80);
    expect(d.signals).toContain(".cursorrules file");
  });

  it("bolt: .bolt/ directory → platform bolt, confidence >= 80", async () => {
    const profile = await buildCodeProfile(join(FIXTURE_ROOT, "bolt-app"));
    const d = detectPlatform(profile);
    expect(d.platform).toBe("bolt");
    expect(d.confidence).toBeGreaterThanOrEqual(80);
    expect(d.signals).toContain(".bolt/ directory");
  });

  it("lovable: lovable.config.ts + lovable-tagger → platform lovable, confidence >= 90 (2 signals)", async () => {
    const profile = await buildCodeProfile(join(FIXTURE_ROOT, "lovable-app"));
    const d = detectPlatform(profile);
    expect(d.platform).toBe("lovable");
    expect(d.confidence).toBeGreaterThanOrEqual(90);
    expect(d.signals.length).toBeGreaterThanOrEqual(2);
  });

  it("replit: .replit file → platform replit, confidence >= 85", async () => {
    const profile = await buildCodeProfile(join(FIXTURE_ROOT, "replit-app"));
    const d = detectPlatform(profile);
    expect(d.platform).toBe("replit");
    expect(d.confidence).toBeGreaterThanOrEqual(85);
    expect(d.signals).toContain(".replit file");
  });

  it("v0: v0.config.ts + Generated-by comment → platform v0, multi-signal", async () => {
    const profile = await buildCodeProfile(join(FIXTURE_ROOT, "v0-app"));
    const d = detectPlatform(profile);
    expect(d.platform).toBe("v0");
    expect(d.confidence).toBeGreaterThanOrEqual(78);
    expect(d.signals).toContain("v0.config file");
  });

  it("base44: base44.json + @base44/sdk → platform base44, confidence >= 90 (2 signals)", async () => {
    const profile = await buildCodeProfile(join(FIXTURE_ROOT, "base44-app"));
    const d = detectPlatform(profile);
    expect(d.platform).toBe("base44");
    expect(d.confidence).toBeGreaterThanOrEqual(90);
    expect(d.signals.length).toBeGreaterThanOrEqual(2);
  });

  it("claude-code: .claude/ + CLAUDE.md → platform claude-code, confidence >= 90 (2 signals)", async () => {
    const profile = await buildCodeProfile(join(FIXTURE_ROOT, "claude-code-app"));
    const d = detectPlatform(profile);
    expect(d.platform).toBe("claude-code");
    expect(d.confidence).toBeGreaterThanOrEqual(90);
    expect(d.signals.length).toBeGreaterThanOrEqual(2);
  });

  it("unknown: plain React project → platform unknown, confidence 0, no signals", async () => {
    const profile = await buildCodeProfile(join(FIXTURE_ROOT, "unknown-app"));
    const d = detectPlatform(profile);
    expect(d.platform).toBe("unknown");
    expect(d.confidence).toBe(0);
    expect(d.signals).toHaveLength(0);
  });
});

// ── Model inference — spec confidence table ───────────────────────────────────

describe("inferModel — confidence table", () => {
  function detect(platform: string, confidence = 90) {
    return inferModel({ platform: platform as never, confidence, signals: ["test"] });
  }

  it("lovable → claude-sonnet-4-6 (conf 80)", () => {
    const m = detect("lovable");
    expect(m.model).toBe("claude-sonnet-4-6");
    expect(m.confidence).toBe(80);
  });

  it("bolt → claude-opus-4-8 (conf 75)", () => {
    const m = detect("bolt");
    expect(m.model).toBe("claude-opus-4-8");
    expect(m.confidence).toBe(75);
  });

  it("cursor → claude-opus-4-8 (conf 55 — user-chosen, lower)", () => {
    const m = detect("cursor");
    expect(m.model).toBe("claude-opus-4-8");
    expect(m.confidence).toBe(55);
  });

  it("v0 → gpt-5.5 (conf 70)", () => {
    const m = detect("v0");
    expect(m.model).toBe("gpt-5.5");
    expect(m.confidence).toBe(70);
  });

  it("replit → gpt-4o (conf 60)", () => {
    const m = detect("replit");
    expect(m.model).toBe("gpt-4o");
    expect(m.confidence).toBe(60);
  });

  it("claude-code → claude-opus-4-8 (conf 70)", () => {
    const m = detect("claude-code");
    expect(m.model).toBe("claude-opus-4-8");
    expect(m.confidence).toBe(70);
  });

  it("base44 → gemini-3.1-pro (conf 65)", () => {
    const m = detect("base44");
    expect(m.model).toBe("gemini-3.1-pro");
    expect(m.confidence).toBe(65);
  });

  it("unknown → model null, confidence 0", () => {
    const m = inferModel({ platform: "unknown", confidence: 0, signals: [] });
    expect(m.model).toBeNull();
    expect(m.confidence).toBe(0);
  });

  it("low-confidence platform detection scales model confidence down", () => {
    // Platform only 50% sure → model confidence should scale
    const m = detect("lovable", 50);
    expect(m.confidence).toBeLessThan(80);
    expect(m.confidence).toBeGreaterThan(0);
  });
});

// ── Ratio — null safety and heuristics ───────────────────────────────────────

describe("computeAiRatio", () => {
  it("returns null (not 0, not a guess) when gitCommits is null", () => {
    const result = computeAiRatio(null);
    expect(result).toBeNull();
  });

  it("returns null for empty commit list", () => {
    expect(computeAiRatio([])).toBeNull();
  });

  it("classifies conventional-commit messages with large diffs as AI", () => {
    const largeAiDiff = "diff --git a/1\n".repeat(25);
    const commits: GitCommit[] = [
      { hash: "abc1234", message: "feat: Add user authentication system", diff: largeAiDiff },
      { hash: "abc1235", message: "feat(auth): Implement OAuth provider", diff: largeAiDiff },
      { hash: "abc1236", message: "Create UserProfile component", diff: largeAiDiff },
    ];
    const ratio = computeAiRatio(commits);
    expect(ratio).not.toBeNull();
    expect(ratio!.likelyAiCommits).toBeGreaterThan(ratio!.likelyHumanCommits);
    expect(ratio!.aiRatio).toBeGreaterThan(0.5);
  });

  it("classifies issue-referenced focused commits as human", () => {
    const smallDiff = "diff --git a/auth.ts\n".repeat(2);
    const commits: GitCommit[] = [
      { hash: "abc1234", message: "Fix broken redirect after OAuth (#234)", diff: smallDiff },
      { hash: "abc1235", message: "wip: debugging token refresh issue", diff: smallDiff },
      { hash: "abc1236", message: "squash: cleanup oops", diff: smallDiff },
    ];
    const ratio = computeAiRatio(commits);
    expect(ratio).not.toBeNull();
    expect(ratio!.likelyHumanCommits).toBeGreaterThan(ratio!.likelyAiCommits);
    expect(ratio!.aiRatio).toBeLessThan(0.5);
  });

  it("aiRatio is in [0, 1]", () => {
    const commits: GitCommit[] = [
      { hash: "a", message: "feat: Add dashboard", diff: "diff --git".repeat(25) },
      { hash: "b", message: "fix bug #99", diff: "" },
    ];
    const ratio = computeAiRatio(commits);
    expect(ratio!.aiRatio).toBeGreaterThanOrEqual(0);
    expect(ratio!.aiRatio).toBeLessThanOrEqual(1);
  });

  it("totalAnalyzed reflects the full commit list (including ambiguous)", () => {
    const commits: GitCommit[] = Array.from({ length: 10 }, (_, i) => ({
      hash: `${i}`,
      message: `Commit ${i}`,  // generic — could go either way
      diff: "",
    }));
    const ratio = computeAiRatio(commits);
    expect(ratio!.totalAnalyzed).toBe(10);
  });
});

// ── Full fingerprint integration ──────────────────────────────────────────────

describe("buildFingerprint — end-to-end", () => {
  it("cursor app: correct platform + model + null ratio (no git)", async () => {
    const profile = await buildCodeProfile(join(FIXTURE_ROOT, "cursor-app"));
    const fp = buildFingerprint(profile);

    expect(fp.platform.platform).toBe("cursor");
    expect(fp.model.model).toBe("claude-opus-4-8");
    expect(fp.model.confidence).toBe(55);
    // Fixture has no git history
    expect(fp.aiRatio).toBeNull();
  });

  it("unknown app: platform unknown, model null, ratio null", async () => {
    const profile = await buildCodeProfile(join(FIXTURE_ROOT, "unknown-app"));
    const fp = buildFingerprint(profile);

    expect(fp.platform.platform).toBe("unknown");
    expect(fp.model.model).toBeNull();
    expect(fp.model.confidence).toBe(0);
    expect(fp.aiRatio).toBeNull();
  });
});

// ── Inline CodeProfile tests (no I/O) ────────────────────────────────────────

describe("detectPlatform — inline profiles, no I/O", () => {
  function makeProfile(files: string[], deps: Record<string, string> = {}): CodeProfile {
    return {
      root: "/project",
      files: files.map(p => ({ path: p, ext: "." + (p.split(".").pop() ?? ""), size: 10, lines: 1, content: "" })),
      packageJson: null,
      dependencies: deps,
      tsConfig: null,
      supabaseMigrations: [],
      apiRoutes: [],
      components: [],
      testFiles: [],
      configFiles: {},
      envExample: null,
      gitCommits: null,
      framework: "unknown",
      hasAuth: false,
      hasDatabase: false,
      hasPayments: false,
      hasUserData: false,
    };
  }

  it("replit.nix alone → replit", () => {
    expect(detectPlatform(makeProfile(["replit.nix"])).platform).toBe("replit");
  });

  it(".bolt/ child file → bolt", () => {
    expect(detectPlatform(makeProfile([".bolt/config.json"])).platform).toBe("bolt");
  });

  it(".cursorrules + .cursor/ → cursor with highest confidence", () => {
    const d = detectPlatform(makeProfile([".cursorrules", ".cursor/rules.json"]));
    expect(d.platform).toBe("cursor");
    expect(d.confidence).toBe(95); // 2 signals → 95
  });

  it("random files with no platform markers → unknown", () => {
    const d = detectPlatform(makeProfile(["src/index.ts", "package.json", "README.md"]));
    expect(d.platform).toBe("unknown");
    expect(d.signals).toHaveLength(0);
  });
});
